# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
remote_theme: "academicpages/academicpages.github.io"

# Site Settings
locale: "en-US"
title: "Junteng Liu"
title_separator: "-"
name: "Junteng Liu"
description: "First-year PhD candidate at HKUST NLP Group"
url: "https://maradeniel-ci.github.io"
baseurl: "/LJT-Homepage"
repository: "maradeniel-ci/LJT-Homepage"
teaser:
logo:
masthead_title:
breadcrumbs: true
words_per_minute: 200
comments:
  provider: false
  disqus:
    shortname:
  discourse:
    server:
  facebook:
    appid:
    num_posts:
    colorscheme:
  utterances:
    theme:
    issue_term:
  giscus:
    repo_id:
    category_id:
    discussion_term:
    reactions_enabled:
    theme:
  staticman:
    branch:
    endpoint:
reCaptcha:
  siteKey:
  secret:
atom_feed:
  path:
  hide:
search:
search_full_content:
search_provider:
algolia:
  application_id:
  index_name:
  search_only_api_key:
  powered_by:
google:
  search_engine_id:
  instant_search:

# SEO Related
google_site_verification:
bing_site_verification:
yandex_site_verification:
naver_site_verification:

# Social Sharing
twitter:
  username: junteng88716710
facebook:
  username:
  app_id:
  publisher:
og_image:
social:
  type:
  name:
  links:

# Analytics
analytics:
  provider: false
  google:
    tracking_id:
    anonymize_ip:

# Site Author
author:
  name: "Junteng Liu"
  avatar:
  bio: "First-year PhD candidate at HKUST NLP Group"
  location:
  email: "jliugi@connect.ust.hk"
  link:
  github: "Vicent0205"
  gitlab:
  bitbucket:
  stackoverflow:
  twitter: "junteng88716710"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  uri:
  house:
  wikipedia:
  weibo:
  zhihu:
  mastodon:
  telephone:
  payment:
  use_meta: false

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone:

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      share: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comment: true

# Collection
collections:
  # _posts
  posts:
    output: true
    permalink: /:collection/:path/
  # _publications
  publications:
    output: true
    permalink: /:collection/:path/
  # _talks
  talks:
    output: true
    permalink: /:collection/:path/
  # _portfolio
  portfolio:
    output: true
    permalink: /:collection/:path/
  # _teaching
  teaching:
    output: true
    permalink: /:collection/:path/

# publication_category
# See https://github.com/academicpages/academicpages.github.io/blob/master/_pages/publications.html
# for usage examples
# publication_category:
#   - title: "Journal Articles"
#     key: "journal"
#   - title: "Conference Papers"
#     key: "conference"
#   - title: "Preprints"
#     key: "preprint"
